### Author --- Prem kumar bharti

## Numpy tutorials

* its a general- purpose array processing package
* It is a scientific computing library for python
* Support large no. of data in the form of multi-dimentional array and matrix
* Use for mathematical calculation like linear algebra , fourier transform etc.

An array is a data structure that stores some value of same data type . In python, this is the main difference between lists and arrays. while python list can contain values corresponding to different data types , arrays in python can only contain values corresponding to same data type

In [1]:
import numpy as np

## Array

In [2]:
arr_1 = np.array([1,2,3,4,5,6])
arr_1

array([1, 2, 3, 4, 5, 6])

In [3]:
n = np.array(range(2 , 11 , 2)) ## Start : end : step

In [4]:
a = np.array([5 , 6 , 7 , "prem"])
a

array(['5', '6', '7', 'prem'], dtype='<U11')

## Arange

In [5]:
#  np.arange(start , end , steps)
b = np.arange(1,5)
print(b)
print(type(b))
print(b.ndim)

[1 2 3 4]
<class 'numpy.ndarray'>
1


## Mathematical Operations

In [6]:
arr1 = np.arange(1,13).reshape(3,4)
arr1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [7]:
arr2 = np.arange(1,13).reshape(3,4)
arr2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [8]:
arr1 + arr2

array([[ 2,  4,  6,  8],
       [10, 12, 14, 16],
       [18, 20, 22, 24]])

In [9]:
arr1 / arr2

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [10]:
arr1 * arr2

array([[  1,   4,   9,  16],
       [ 25,  36,  49,  64],
       [ 81, 100, 121, 144]])